// products
export const SAVE_PRODUCT = 'SAVE_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const CLEAR_CURRENT_PRODUCT = 'CLEAR_CURRENT_PRODUCT';
export const PRODUCT_IS_LOADING = 'PRODUCT_IS_LOADING';

// modals
export const TOGGLE_PRODUCT_WINDOW = 'TOGGLE_PRODUCT_WINDOW';
export const TOGGLE_SHOPLIST_WINDOW = 'TOGGLE_SHOPLIST_WINDOW';

// shoplist
export const ADD_SHOPLIST = 'ADD_SHOPLIST';
export const DELETE_SHOPLIST = 'DELETE_SHOPLIST';
export const UPDATE_SHOPLIST = 'UPDATE_SHOPLIST';
export const GET_SHOPLIST = 'GET_SHOPLIST';
export const SHOPLIST_IS_LOADING = 'SHOPLIST_IS_LOADING';
export const TOGGLE_PRODUCT_IN_SHOPLIST = 'TOGGLE_PRODUCT_IN_SHOPLIST';
export const CLEAN_CHOOSEN_PRODUCTS_IN_SHOPLIST = 'CLEAN_CHOOSEN_PRODUCTS_IN_SHOPLIST';
